### ISSUE TITLE
Extrair classes candidatas

### ISSUE THREAD

**Issue by gahhhenrikk** [gahhhenrikk/gerenciador-de-equipes#3]
> Exemplo:
- Nome
- Descrição
- Atores
- Pré-Condições
- Pós-Condições
- Requisitos especiais
- Fluxo de Eventos (Básico e Alternativos)

**Comment by gahhhenrikk** [comment]
ouve um engano, a tarefa nao foi completada

**Comment by gahhhenrikk** [comment]
deu errado

**Comment by AlbericoD** [comment]
então, faz 5 dias isso
